ShopTARge24/Models/Spaceships/SpaceshipCreateUpdateViewModel.cs
namespace ShopTARge24.Models.Spaceships
{
    public class SpaceshipCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Classification { get; set; }
        public DateTime? BuiltDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARge24/Models/Spaceships/SpaceshipDeleteViewModel.cs
namespace ShopTARge24.Models.Spaceships
{
    public class SpaceshipDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Classification { get; set; }
        public DateTime? BuiltDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARge24/Models/Spaceships/SpaceshipDetailsViewModel.cs
namespace ShopTARge24.Models.Spaceships
{
    public class SpaceshipDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Classification { get; set; }
        public DateTime? BuiltDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARge24/Models/Spaceships/SpaceshipIndexViewModel.cs
namespace ShopTARge24.Models.Spaceships
{
    public class SpaceshipIndexViewModel
    {
        public Guid? Id { get; set; }

        public string? Name { get; set; }

        public string? Classification { get; set; }

        public DateTime? BuiltDate { get; set; }

        public int? Crew { get; set; }

        public int? EnginePower { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }


    }
}

ShopTARge24/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ShopTARge24.Core.Domain;
using ShopTARge24.Core.Dto;
using ShopTARge24.Core.ServiceInterface;
using ShopTARge24.Data;
using ShopTARge24.Models.Spaceships;

namespace ShopTARge24.Controllers
{

    // F11 näitab kogu koodi järjestuse
    public class SpaceshipsController : Controller
    {
        private readonly ShopTARge24Context _context;
        private readonly ISpaceshipServices _spaceshipServices;

        public SpaceshipsController
            (
                ShopTARge24Context context,
                ISpaceshipServices spaceshipServices
            )
        {
            _context = context;
            _spaceshipServices = spaceshipServices;
        }


        public IActionResult Index()
        {
            var result = _context.Spaceships
                .Select(x => new SpaceshipIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Classification = x.Classification,
                    BuiltDate = x.BuiltDate,
                    Crew = x.Crew,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            SpaceshipCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }


        [HttpPost]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt
            };

            var result = await _spaceshipServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var vm = new SpaceshipCreateUpdateViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            //Tuleb dto ja vm omavahel ära mappida 
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt
            };

            var result = await _spaceshipServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));

        }

            // MINU VERSIOON -> 
            //  var vm = await _spaceshipServices.Update(dto);

            //  if (vm == null)
            //  {
            //      return RedirectToAction(nameof(Index));
            //  }

            //  return RedirectToAction(nameof(Index));

     
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var vm = new SpaceshipDeleteViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var spaceship = await _spaceshipServices.Delete(id);

            if (spaceship == null)
            {
                return RedirectToAction(nameof(Index));
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            // kasutada service klassi meetodit, et info kätte saada
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }
            // toimub viewModeliga mappimine
            var vm = new SpaceshipDetailsViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;



            // minu versioon ->  var vm = await _context.Spaceships
            //                   .FirstOrDefaultAsync(x => x.Id == id);

            // _context.Spaceships.GetService(id);
            // await _context.SaveChangesAsync();
            // return View(vm);

            return View(vm);

        }
    }
}

ShopTARge24/Views/Spaceships/CreateUpdate.cshtml
@model ShopTARge24.Models.Spaceships.SpaceshipCreateUpdateViewModel

@* Vaja teha loogika, kus uute andmete sisetamisel näitab Create ja uuendamisel Update *@
@if (Model.Id.HasValue)
{
	<h1>Update</h1>
}
else
{
	<h1>Create</h1>
}

<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="Id" type="hidden" />
		<input asp-for="CreatedAt" type="hidden" />
		<input asp-for="ModifiedAt" type="hidden" />

		<div class="form-group row">
			<label asp-for="Name" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Name" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="Classification" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Classification" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="BuiltDate" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="Crew" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="Crew" class="form-control" />
			</div>
		</div>

		<div class="form-group row">
			<label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
			<div class="col-sm-10">
				<input asp-for="EnginePower" class="form-control" />
			</div>
		</div>

		@if (Model.Id.HasValue)
		{
			<input asp-action="update" asp-controller="spaceships" type="submit" class=" btn btn-primary" value="Update" />

		} else
		{
			<input asp-action="create" asp-controller="spaceships" type="submit" class=" btn btn-primary" value="Create"/>
		}

		
	</form>

</div>

ShopTARge24/Views/Spaceships/Delete.cshtml
@model ShopTARge24.Models.Spaceships.SpaceshipDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Spaceship</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Classification" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Classification)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    <hr />
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>
    </form>

</div>

ShopTARge24/Views/Spaceships/Details.cshtml
@model ShopTARge24.Models.Spaceships.SpaceshipDetailsViewModel

<h1>Details</h1>

ShopTARge24/Views/Spaceships/Index.cshtml
@* Tere Gervin! *@
@model IEnumerable<ShopTARge24.Models.Spaceships.SpaceshipIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Spaceships" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Spaceships
</div>
<form method="get">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Built Date</th>
                <th scope="col">Crew</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var spaceship in Model)
                {
                    <tr>
                        <td>@rowNumber</td>
                        <td>@spaceship.Name</td>
                        <td>@spaceship.Classification</td>
                        <td>@spaceship.BuiltDate</td>
                        <td>@spaceship.Crew</td>
                        <td>
                            <a asp-action="details" asp-controller="spaceships" asp-route-id="@spaceship.Id" class="btn btn-primary">Details</a>
                            <a asp-action="update" asp-controller="spaceships" asp-route-id="@spaceship.Id" class="btn btn-primary">Update</a>
                            <a asp-action="delete" asp-controller="spaceships" asp-route-id="@spaceship.Id" class="btn btn-outline-danger">Delete</a>
                        </td>
                </tr>
                rowNumber += 1;
            }
        </tbody>
    </table>
</form>